### ISSUE TITLE
How to mount config file into docker container

### ISSUE THREAD

**Issue by budimanjojo** [markusressel/keel-telegram-bot#23]
Hello, I want to try the prebuilt container image from docker hub in my kubernetes cluster but it fails to start with this error:
```
python: can't open file './keel_telegram_bot/main.py': [Errno 2] No such file or directory
```
I already tried the all the tags (v1.0.0, 1.2.0, latest), all of them failed with this error.

**Comment by budimanjojo** [comment]
> I am using the `latest` tag myself in production, not sure what the issue is?
> This is the sidecar that I run next to the keel.sh container:
> 
I think I know what is the problem. I mounted the secret as file in /app/keel-telegram-bot.yaml
If I don't mount any volume the pod will run for a while before error out with invalid password value error.

Can you tell me where should I mount the config file to? Or is there a command argument to use file from certain path?
Here's my deployment file
```
    spec:
      containers:
      - name: keel-telegram-bot
        image: markusressel/keel-telegram-bot
        imagePullPolicy: IfNotPresent
        ports:
        - name: bot-port
          protocol: TCP
          containerPort: 9300
        volumeMounts:
        - name: bot-config
          mountPath: /app
      volumes:
      - name: bot-config
        secret:
          secretName: telegram-bot-secrets
```
And here's my secret file:
```
apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secrets
  namespace: keel-system
  labels:
    app.kubernetes.io/name: keel-telegram-bot
type: Opaque
stringData:
  keel-telegram-bot.yml: |
    keel-telegram-bot:
      log_level: warning
      keel:
        host: keel-svc
        port: 9300
     .......
```

**Comment by markusressel** [comment]
I use a configmap to mount the config file with basic configuration options, and a secret from which I mount keys as environment variables to override passwords in the configmap/config file. You can see the mount configuration for both in my previous post. 

This is the volume definition:

```
volumes:
  - configMap:
      items:
      - key: config
        path: keel-telegram-bot.yml
      name: keel-telegram-bot
      optional: false
    name: config
```

and the configmap:

```
apiVersion: v1
data:
  config: |-
    keel-telegram-bot:
      log_level: debug
      keel:
        host: localhost
        port: 9300
        ssl: false
      [...]
kind: ConfigMap
metadata:
  name: keel-telegram-bot
  namespace: keel
```
